"""
CRUD operations for all database models
"""

from crud import (
    client,
    demande,
    demande_contact,
    demande_team_building,
    demande_tourisme,
    newsletter,
    offre,
    offre_tourisme,
    proforma,
    site,
    activite,
    jeu,
    activite_jeu,
    activite_benevole,
    activite_materiel,
    personnel,
    affectation,
    materiel,
    depense,
    benevole,
    chat,
    dashboard_admin,
    contact_akan,
    circuit_touristique,
    role,
    utilisateur,
)

__all__ = [
    "client",
    "demande",
    "demande_contact",
    "demande_team_building",
    "demande_tourisme",
    "newsletter",
    "offre",
    "offre_tourisme",
    "proforma",
    "site",
    "activite",
    "jeu",
    "activite_jeu",
    "activite_benevole",
    "activite_materiel",
    "personnel",
    "affectation",
    "materiel",
    "depense",
    "benevole",
    "chat",
    "dashboard_admin",
    "contact_akan",
    "circuit_touristique",
    "role",
    "utilisateur",
]

